intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.

lib{Day01}: {mxx cxx}{**} $impl_libs $intf_libs

# Build options
{bmia obja}{*}: cxx.poptions += -DDAY01_STATIC_BUILD
{bmis objs}{*}: cxx.poptions += -DDAY01_SHARED_BUILD

# Export options.
lib{Day01}:
{
  cxx.export.libs = $intf_libs
}

# For pre-releases use the complete version to make sure they cannot be used
# in place of another pre-release or the final version. See the version module
# for details on the version.* variable values.
if $version.pre_release
  lib{Day01}: bin.lib.version = "-$version.project_id"
else
  lib{Day01}: bin.lib.version = "-$version.major.$version.minor"

# Install into the Day01/ subdirectory of, say, /usr/include/
# recreating subdirectories.
{mxx}{*}:
{
  install         = include/AdventOfCode2022/Day01/
  install.subdirs = true
}
